### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by n-wissam** [kelciour/google-translate#25]
When I try to translate a word I get the following error:
```
Error:

Traceback (most recent call last):
  File "/home/wissam/.local/share/Anki2/addons21/1536291224/__init__.py", line 465, in accept
    translation = self.translator.translate(urllib.parse.unquote(query), src=self.sourceLangCode, dest=self.targetLangCode)
  File "/home/wissam/.local/lib/python3.10/site-packages/googletrans/client.py", line 182, in translate
    data = self._translate(text, dest, src, kwargs)
  File "/home/wissam/.local/lib/python3.10/site-packages/googletrans/client.py", line 78, in _translate
    token = self.token_acquirer.do(text)
  File "/home/wissam/.local/lib/python3.10/site-packages/googletrans/gtoken.py", line 194, in do
    self._update()
  File "/home/wissam/.local/lib/python3.10/site-packages/googletrans/gtoken.py", line 62, in _update
    code = self.RE_TKK.search(r.text).group(1).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'
```

And previously I got this error but I couldn't produce it again:
```
Error:

Traceback (most recent call last):
  File "/home/wissam/.local/share/Anki2/addons21/1536291224/__init__.py", line 466, in accept
    data = translation.extra_data['parsed']
KeyError: 'parsed'
```

Anki version: 2.1.54
The addone was updated today

**Comment by ghost** [comment]
Getting the same error
