### ISSUE TITLE
Error report. The plugin started to report this error and didn't work from yesterday. Could you fix this? Thank you! (It's really a very helpful plugin!!!)

### ISSUE THREAD

**Issue by Chase518** [kelciour/google-translate#27]
Error:

Traceback (most recent call last):
  File "urllib3.connection", line 174, in _new_conn
  File "urllib3.util.connection", line 95, in create_connection
  File "urllib3.util.connection", line 85, in create_connection
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3.connectionpool", line 703, in urlopen
  File "urllib3.connectionpool", line 386, in _make_request
  File "urllib3.connectionpool", line 1040, in _validate_conn
  File "urllib3.connection", line 358, in connect
  File "urllib3.connection", line 179, in _new_conn
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000002070038C940>, 'Connection to translate.googleapis.com timed out. (connect timeout=15)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests.adapters", line 440, in send
  File "urllib3.connectionpool", line 785, in urlopen
  File "urllib3.util.retry", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='translate.googleapis.com', port=443): Max retries exceeded with url: /translate_a/single?client=gtx&sl=de&tl=en&dt=t&q=Er%20wird%20morgen%20nach%20Hannover%20fliegen. (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002070038C940>, 'Connection to translate.googleapis.com timed out. (connect timeout=15)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "…\Roaming\Anki2\addons21\1536291224\__init__.py", line 424, in accept
    result = translate(query, options)
  File "…\Roaming\Anki2\addons21\1536291224\__init__.py", line 50, in translate
    r = requests.get(GOOGLE_TRANSLATE_URL, headers=headers, timeout=15)
  File "requests.api", line 75, in get
  File "requests.api", line 61, in request
  File "requests.sessions", line 529, in request
  File "requests.sessions", line 645, in send
  File "requests.adapters", line 507, in send
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='translate.googleapis.com', port=443): Max retries exceeded with url: /translate_a/single?client=gtx&sl=de&tl=en&dt=t&q=Er%20wird%20morgen%20nach%20Hannover%20fliegen. (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000002070038C940>, 'Connection to translate.googleapis.com timed out. (connect timeout=15)'))

**Comment by Elias-W1** [comment]
https://translate.googleapis.com/translate_a/single?client=gtx&sl=de&tl=en&dt=t&q=Er%20wird%20morgen%20nach%20Hannover%20fliegen

The url works fine for me. Maybe an Ip ban? Does the issue still arise today?

**Comment by Chase518** [comment]
> https://translate.googleapis.com/translate_a/single?client=gtx&sl=de&tl=en&dt=t&q=Er%20wird%20morgen%20nach%20Hannover%20fliegen
> 
> The url works fine for me. Maybe an Ip ban? Does the issue still arise today?

（ So the plugin works well on your computer? ） Yes, the problem is still there. I'm not sure about what an IP ban is, but we do have a Great Firewall here. However, the plugin worked well before without any additional help. And I have tried to use a proxy, but it gave me a different error… 
 
Error:

Traceback (most recent call last):
  File "urllib3.connectionpool", line 700, in urlopen
  File "urllib3.connectionpool", line 994, in _prepare_proxy
  File "urllib3.connection", line 364, in connect
  File "urllib3.connection", line 499, in _connect_tls_proxy
  File "urllib3.util.ssl_", line 453, in ssl_wrap_socket
  File "urllib3.util.ssl_", line 495, in _ssl_wrap_socket_impl
  File "ssl", line 500, in wrap_socket
  File "ssl", line 1040, in _create
  File "ssl", line 1309, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests.adapters", line 440, in send
  File "urllib3.connectionpool", line 785, in urlopen
  File "urllib3.util.retry", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='translate.googleapis.com', port=443): Max retries exceeded with url: /translate_a/single?client=gtx&sl=de&tl=en&dt=t&q=Er%20beherrscht%20die%20Theorie%20seines%20Faches%2C%20aber%20er%20hat%20noch%20wenig%20praktische%20Erfahrungen. (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "…\AppData\Roaming\Anki2\addons21\1536291224\__init__.py", line 424, in accept
    result = translate(query, options)
  File "…\AppData\Roaming\Anki2\addons21\1536291224\__init__.py", line 50, in translate
    r = requests.get(GOOGLE_TRANSLATE_URL, headers=headers, timeout=15)
  File "requests.api", line 75, in get
  File "requests.api", line 61, in request
  File "requests.sessions", line 529, in request
  File "requests.sessions", line 645, in send
  File "requests.adapters", line 517, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='translate.googleapis.com', port=443): Max retries exceeded with url: /translate_a/single?client=gtx&sl=de&tl=en&dt=t&q=Er%20beherrscht%20die%20Theorie%20seines%20Faches%2C%20aber%20er%20hat%20noch%20wenig%20praktische%20Erfahrungen. (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

**Comment by Chase518** [comment]
Finally!, I've found the solution to this problem here: https://docs.ankiweb.net/syncing.html?highlight=proxy#proxies

"Anki will only be able to pick up your system settings if a proxy is manually configured, and does not require a password. If your system uses automatic proxy setup, or uses a proxy that requires a username and password, you will need to manually tell Anki the proxy configuration.

To tell Anki your proxy settings, define a HTTPS_PROXY environmental variable that points to the proxy server."

So the problem was in deeded caused by the G. F. W. And I need some extra steps to make my Anki to have access to  my proxy service to reconnect to the Google Translate.

**Comment by Chase518** [comment]
Finally!, I've found the solution to this problem here: https://docs.ankiweb.net/syncing.html?highlight=proxy#proxies

"Anki will only be able to pick up your system settings if a proxy is manually configured, and does not require a password. If your system uses automatic proxy setup, or uses a proxy that requires a username and password, you will need to manually tell Anki the proxy configuration.

To tell Anki your proxy settings, define a HTTPS_PROXY environmental variable that points to the proxy server."

So the problem was indeed caused by the Great Firewall. And I need some extra steps to make my Anki to have access to  my proxy service to reconnect to the Google Translate.
