### ISSUE TITLE
google translate extention for anki

### ISSUE THREAD

**Issue by Katauoon** [kelciour/google-translate#36]
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
Platform: Windows-10-10.0.22000

When loading Google Translate:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\Asus\AppData\Roaming\Anki2\addons21\1536291224\__init__.py", line 24, in <module>
    from . import form
  File "C:\Users\Asus\AppData\Roaming\Anki2\addons21\1536291224\form.py", line 9, in <module>
    from PyQt6 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt6'

**Comment by kelciour** [comment]
Thank you! It was fixed!
