### ISSUE TITLE
Worked for few cards after that stopped

### ISSUE THREAD

**Issue by nnbveh** [kelciour/google-translate#40]
Anki 24.04.1 (ccd9ca1a)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "anki.notes", line 154, in _field_index
KeyError: 'Jlab-Kanji'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\nnbveh\AppData\Roaming\Anki2\addons21\972129549\__init__.py", line 249, in accept
    self.translate()
  File "C:\Users\nnbveh\AppData\Roaming\Anki2\addons21\972129549\__init__.py", line 396, in translate
    raise exception
  File "C:\Users\nnbveh\AppData\Roaming\Anki2\addons21\972129549\__init__.py", line 278, in translate
    if not note[self.sourceField]:
  File "anki.notes", line 159, in __getitem__
  File "anki.notes", line 156, in _field_index
KeyError: 'Jlab-Kanji'

**Comment by kelciour** [comment]
The add-on can't handle multiple note types with no source or target fields existing.

But there's a workaround, search for `Jlab-Kanji:_*` in the card browser and try to translate only these notes.
